name: "Lint"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:

  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v4.2.2"

        - name: Install uv
          uses: astral-sh/setup-uv@4db96194c378173c656ce18a155ffc14a9fc4355 # v3

        - name: Set up Python
          run: uv python install 3.13

        - name: Install the project
          run: uv sync --all-extras --dev 

        - name: "Run ruff"
          run: uvx ruff check .

        - name: "Format with ruff"
          run: uvx ruff format . --check

